local dap = require("dap")
local dapui = require("dapui")
local dap_python = require("lib.dap.python")
dap.adapters.python = dap_python.adapter
dap.configurations.python = dap_python.configuration
require("nvim-dap-virtual-text").setup()
dapui.setup()
dap.listeners.before.attach.dapui_config = function()
    dapui.open()
end
dap.listeners.before.launch.dapui_config = function()
    dapui.open()
end
dap.listeners.before.event_terminated.dapui_config = function()
    dapui.close()
end
dap.listeners.before.event_exited.dapui_config = function()
    dapui.close()
end
vim.keymap.set("n", "<leader>bb", function()
    dap.toggle_breakpoint()
end)
vim.keymap.set("n", "<leader>vv", function()
    dapui.toggle()
end)
vim.keymap.set("n", "<leader>df", function()
    dapui.float_element()
end)
vim.keymap.set("n", "<leader>de", function()
    dapui.eval()
end)
vim.keymap.set("n", "<leader>dk", function()
    dap.continue()
end)
vim.keymap.set("n", "<leader>dl", function()
    dap.run_last()
end)
vim.keymap.set("n", "<leader>dn", function()
    dap.step_over()
end)
vim.keymap.set("n", "<leader>di", function()
    dap.step_into()
end)
vim.keymap.set("n", "<leader>do", function()
    dap.step_out()
end)
vim.keymap.set("n", "<leader>dt", function()
    dap.terminate()
end)
